### ISSUE TITLE
HTTP_ERROR 400 - Bad Request

### ISSUE THREAD

**Issue by guelinator** [thetvdb/tvdb-v4-python#22]
when trying your example (except exchanging the api_key) i get an HTTP ERROR 400: Bad Request

**Comment by MastaG** [comment]
same here, Just received my developers v4 API key.
The thing aint working.

**Comment by antheaezzell** [comment]
@guelinator and @MastaG we are looking into this now. Thank you for reporting.

I have an internal ticket for our reference - https://mediamorph.atlassian.net/browse/TVD-2794

**Comment by maxifwortman** [comment]
@guelinator @MastaG this is because you need to include your pin in the login like this:

`tvdb = tvdb_v4_official.TVDB("APIKEY", pin="YOUR PIN HERE")`

**Comment by Dobatymo** [comment]
@maxifwortman there is no pin for dev keys.

**Comment by antheaezzell** [comment]
Hi @guelinator and @MastaG we updated the python library in the last release and our developer just tested again. We think it should be working if you would like to test.

**Comment by antheaezzell** [comment]
@guelinator and @MastaG this should be resolved and the ppyi was recently updated as well. Let me know if I can close this out?

**Comment by dzhl** [comment]
what‘ the pin,i don't have pin,only have V4 apikey,how can i reslove it?

**Comment by rtaft** [comment]
Developer keys still do not work.
Exception: Code:HTTP Error 400: Bad Request, InvalidValueType: pin required

**Comment by szsori** [comment]
Hello @dzhl and @rtaft . As described when you created your API keys, they come in two varieties: contract and subscriber-supported.  By selecting the subscriber-supported option, you must log into the API with both an API key and a user-specific PIN.  PINs should be per-user and are obtained with a TheTVDB subscription (https://thetvdb.com/subscribe).

If you prefer to set up a contractual API key, please create a new key and select that option.  We have to approve those keys and may have additional requirements related to attribution.

**Comment by rtaft** [comment]
So you have to be a paying subscriber to develop against the API, but free to scrape?
